#Financial Product Complaint Classification and Summarization

## **Business Context**

### **Description**
*In the modern financial industry, customer complaints play a crucial role in identifying areas where financial institutions can improve their services. Effectively categorizing these complaints into specific product categories, such as credit reports, student loans, or money transfers, is essential for addressing customer concerns promptly by routing the tickets to relevant personnel. Leveraging Generative AI for text classification can help financial institutions better understand customer grievances and respond more efficiently. Apart from this, a summary of the customer complaint helps the support personnel quickly grasp the gist of the grievance*

### **Objective**
*The primary goal of this project is to utilize Generative AI techniques to improve the classification and summarization of customer complaints in the financial sector.
Specifically, the project will focus on:*

1. **Text-to-Label Classification:** *Implementing Zero-shot and Few-shot prompting methods to accurately classify customer complaints into relevant product categories.*
2. **Text-to-Text Summarization:** *Using Zero-shot prompting to generate concise summaries of customer complaints, enabling more personalized and effective responses.*

# **Section 1 : Setting Up for Prompt Engineering with Mistral Model**

### **Install & Importing neccessary libraries**

In [5]:
!apt-get update
!apt-get install -y ninja-build cmake
!pip install ipywidgets --upgrade

0% [Working]

Hit:1 https://cli.github.com/packages stable InRelease

0% [Connecting to archive.ubuntu.com] [Connecting to security.ubuntu.com (91.18

Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ninja-build is already the newest version (1.10.1-1).
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 123 not upgraded.
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets) (7.34.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets) (5.7.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.12/dist-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.12/dist-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets) (0.6.0)

In [6]:
import torch

In [7]:
# This part of code will skip all the un-necessary warnings which can occur during the execution of this project.
import warnings
warnings.filterwarnings("ignore", category=Warning)

In [8]:
# Installation for GPU llama-cpp-python==0.2.69
!CMAKE_ARGS="-DLLAMA_CUDA=on" pip install llama-cpp-python==0.2.69
# For downloading the models from HF Hub
!pip install huggingface_hub

Requirement already satisfied: llama-cpp-python==0.2.69 in /usr/local/lib/python3.12/dist-packages (0.2.69)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python==0.2.69) (4.15.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python==0.2.69) (2.0.2)
Requirement already satisfied: diskcache>=5.6.1 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python==0.2.69) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python==0.2.69) (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.3->llama-cpp-python==0.2.69) (3.0.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

In [9]:
!pip install evaluate #HF to evaluate metrics for ML models
!pip install bert-score #how similar 2 sentences are using contextual embeddings from BERT like models

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.0 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.10.0+cu128)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.25.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.0.0->bert-score) (1.4.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.6.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.2.25)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.24.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.1.2)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 6.2 MB/s eta 0:00:00
Installing collected packages: bert-score
Successfully installed bert-score-0.3.13

In [10]:
!pip freeze > requirement.txt

In [11]:
# Basic Imports for Libraries
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

import pandas as pd
import numpy as np
from tqdm import tqdm
import json
import re

import torch
import evaluate

# from google.colab import drive
import locale

###1: Importing Libaries and Mistral Model

In [12]:
from huggingface_hub import hf_hub_download
from llama_cpp import Llama

In [13]:
model_name_or_path = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_basename = "mistral-7b-instruct-v0.2.Q5_K_M.gguf"

In [14]:
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
    )

mistral-7b-instruct-v0.2.Q5_K_M.gguf:   0%|          | 0.00/5.13G [00:00<?, ?B/s]

In [15]:
lcpp_llm = Llama(
        model_path=model_path, #GGUF model file # mistral-7b
        n_threads=2,  # no CPU cores used
        n_batch=512,  # tokens processed per computation step
        n_gpu_layers=43,  # how many model layers are offloaded to GPU
        n_ctx=4096,  # context window size
    )

llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from /root/.cache/huggingface/hub/models--TheBloke--Mistral-7B-Instruct-v0.2-GGUF/snapshots/3a6fbf4a41a1d52e415a4958cde6856d34b2db93/mistral-7b-instruct-v0.2.Q5_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.2
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 17
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q5_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.78 GiB (5.67 BPW)
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.30 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    85.94 MiB
llm_load_tensors:      CUDA0 buffer size =  4807.05 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =   512.00 MiB
llama_new_context_with_model: KV self size  =  512.00 MiB, K (f16):  256.00 MiB, V (f16):  256.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.12 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   296.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    16.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
Model metadata: {'tokenizer.chat_template': "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}", 'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.padding_token_id': '0', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.rope.freq_base': '1000000.000000', 'llama.context_length': '32768', 'general.name': 'mistralai_mistral-7b-instruct-v0.2', 'tokenizer.ggml.add_bos_token': 'true', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '17'}
Guessed chat format: mistral-instruct

# **Text to Label generation**

In [46]:
system_message = """
You are an expert financial complaint classification assistant.
Your task is to read a customer's complaint narrative and classify it into the correct product category.

Choose only one category from the following list (return exactly as written):
credit_card, retail_banking, credit_reporting, mortgages_and_loans, debt_collection.

Return only the category name. Do not provide explanations.
"""

In [47]:
zero_shot_prompt_template = """<s>[INST]
<<SYS>>
{system_message}
<</SYS>>

Customer Complaint:
{user_input}

Product Category:
[/INST]

"""

In [18]:
def generate_prompt(system_message,user_input):
    prompt=zero_shot_prompt_template.format(system_message=system_message,user_input=user_input) #zero shot prompt
    return prompt

In [19]:
def generate_mistral_response(input_text):

    # Combine user_prompt and system_message to create the prompt
    prompt = generate_prompt(system_message,input_text)

    # Define the Llama model along with its parameters for generating a response
    response = lcpp_llm(
        prompt=prompt,
        max_tokens=1200,
        temperature=0,
        top_p = 0.95,
        repeat_penalty=1.2,
        top_k=50,
        stop=["</s>"],
        echo=False
    )

    # Extract and return the response text
    response_text = response["choices"][0]["text"].strip()
    print(response_text)
    return response_text

In [21]:
data = pd.read_csv("/content/Complaints_classification.csv")

In [22]:
# Randomly select 30 rows
new_data = data.sample(n=30, random_state=40)

In [23]:
print(new_data.head())

              product                                          narrative  \
167    retail_banking  fraudulent charge totaling made capital one ch...
169  credit_reporting  block except otherwise provided section consum...
461       credit_card  usaa master plan collect cancellation debt usa...
253  credit_reporting  block except otherwise provided section consum...
42   credit_reporting  open account acct opened balance account acct ...

                                               summary
167  A fraudulent charge was made on the individual...
169  The text outlines various stipulations regardi...
461  The input appears to be a complaint about USAA...
253  The text pertains to the stipulations and oper...
42   The input is about various accounts being open...

In [24]:
#create a new column DF 'mistral_response' & populate it with responses generated by applying the 'general_mistral_response' function to each 'narrative' in the DF & prepare the mistral_response_cleaned col using extract_category function
new_data['mistral_response'] = new_data['narrative'].apply(lambda x: generate_mistral_response(x))

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.97 ms /     6 runs   (    0.66 ms per token,  1510.19 tokens per second)
llama_print_timings: prompt eval time =     649.20 ms /   338 tokens (    1.92 ms per token,   520.64 tokens per second)
llama_print_timings:        eval time =     139.62 ms /     5 runs   (   27.92 ms per token,    35.81 tokens per second)
llama_print_timings:       total time =     817.65 ms /   343 tokens
Llama.generate: prefix-match hit

credit_card.

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.17 ms /     6 runs   (    0.53 ms per token,  1893.34 tokens per second)
llama_print_timings: prompt eval time =     513.79 ms /   512 tokens (    1.00 ms per token,   996.52 tokens per second)
llama_print_timings:        eval time =     150.38 ms /     5 runs   (   30.08 ms per token,    33.25 tokens per second)
llama_print_timings:       total time =     684.44 ms /   517 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.27 ms /     6 runs   (    0.54 ms per token,  1835.42 tokens per second)
llama_print_timings: prompt eval time =     320.88 ms /   189 tokens (    1.70 ms per token,   589.01 tokens per second)
llama_print_timings:        eval time =     146.58 ms /     5 runs   (   29.32 ms per token,    34.11 tokens per second)
llama_print_timings:       total time =     488.83 ms /   194 tokens
Llama.generate: prefix-match hit

debt_collection.

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.31 ms /     6 runs   (    0.55 ms per token,  1813.24 tokens per second)
llama_print_timings: prompt eval time =     513.65 ms /   512 tokens (    1.00 ms per token,   996.78 tokens per second)
llama_print_timings:        eval time =     154.43 ms /     5 runs   (   30.89 ms per token,    32.38 tokens per second)
llama_print_timings:       total time =     688.61 ms /   517 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       2.72 ms /     6 runs   (    0.45 ms per token,  2202.64 tokens per second)
llama_print_timings: prompt eval time =     200.57 ms /    81 tokens (    2.48 ms per token,   403.86 tokens per second)
llama_print_timings:        eval time =     148.18 ms /     5 runs   (   29.64 ms per token,    33.74 tokens per second)
llama_print_timings:       total time =     368.91 ms /    86 tokens
Llama.generate: prefix-match hit

retail_banking

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.30 ms /     6 runs   (    0.55 ms per token,  1820.39 tokens per second)
llama_print_timings: prompt eval time =     487.54 ms /   427 tokens (    1.14 ms per token,   875.83 tokens per second)
llama_print_timings:        eval time =     154.14 ms /     5 runs   (   30.83 ms per token,    32.44 tokens per second)
llama_print_timings:       total time =     662.14 ms /   432 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       5.51 ms /    10 runs   (    0.55 ms per token,  1815.54 tokens per second)
llama_print_timings: prompt eval time =     206.95 ms /    94 tokens (    2.20 ms per token,   454.21 tokens per second)
llama_print_timings:        eval time =     268.05 ms /     9 runs   (   29.78 ms per token,    33.58 tokens per second)
llama_print_timings:       total time =     507.39 ms /   103 tokens
Llama.generate: prefix-match hit

mortgages_and_loans

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.44 ms /     6 runs   (    0.57 ms per token,  1742.16 tokens per second)
llama_print_timings: prompt eval time =     486.62 ms /   427 tokens (    1.14 ms per token,   877.47 tokens per second)
llama_print_timings:        eval time =     155.28 ms /     5 runs   (   31.06 ms per token,    32.20 tokens per second)
llama_print_timings:       total time =     664.63 ms /   432 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.20 ms /     6 runs   (    0.53 ms per token,  1877.35 tokens per second)
llama_print_timings: prompt eval time =     487.06 ms /   439 tokens (    1.11 ms per token,   901.33 tokens per second)
llama_print_timings:        eval time =     151.68 ms /     5 runs   (   30.34 ms per token,    32.97 tokens per second)
llama_print_timings:       total time =     658.79 ms /   444 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.04 ms /     6 runs   (    0.51 ms per token,  1974.33 tokens per second)
llama_print_timings: prompt eval time =     488.45 ms /   427 tokens (    1.14 ms per token,   874.20 tokens per second)
llama_print_timings:        eval time =     156.31 ms /     5 runs   (   31.26 ms per token,    31.99 tokens per second)
llama_print_timings:       total time =     664.33 ms /   432 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.66 ms /     6 runs   (    0.61 ms per token,  1638.45 tokens per second)
llama_print_timings: prompt eval time =     267.95 ms /   154 tokens (    1.74 ms per token,   574.74 tokens per second)
llama_print_timings:        eval time =     149.85 ms /     5 runs   (   29.97 ms per token,    33.37 tokens per second)
llama_print_timings:       total time =     448.19 ms /   159 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.39 ms /     6 runs   (    0.56 ms per token,  1771.48 tokens per second)
llama_print_timings: prompt eval time =     601.64 ms /   518 tokens (    1.16 ms per token,   860.98 tokens per second)
llama_print_timings:        eval time =     159.39 ms /     5 runs   (   31.88 ms per token,    31.37 tokens per second)
llama_print_timings:       total time =     785.54 ms /   523 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.03 ms /     6 runs   (    0.51 ms per token,  1977.59 tokens per second)
llama_print_timings: prompt eval time =     489.16 ms /   427 tokens (    1.15 ms per token,   872.93 tokens per second)
llama_print_timings:        eval time =     154.78 ms /     5 runs   (   30.96 ms per token,    32.30 tokens per second)
llama_print_timings:       total time =     663.86 ms /   432 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       5.69 ms /    10 runs   (    0.57 ms per token,  1756.23 tokens per second)
llama_print_timings: prompt eval time =     296.83 ms /   239 tokens (    1.24 ms per token,   805.19 tokens per second)
llama_print_timings:        eval time =     277.27 ms /     9 runs   (   30.81 ms per token,    32.46 tokens per second)
llama_print_timings:       total time =     610.38 ms /   248 tokens
Llama.generate: prefix-match hit

mortgages_and_loans

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.11 ms /     6 runs   (    0.52 ms per token,  1930.50 tokens per second)
llama_print_timings: prompt eval time =     587.11 ms /   518 tokens (    1.13 ms per token,   882.29 tokens per second)
llama_print_timings:        eval time =     157.41 ms /     5 runs   (   31.48 ms per token,    31.76 tokens per second)
llama_print_timings:       total time =     765.93 ms /   523 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       4.05 ms /     6 runs   (    0.68 ms per token,  1480.02 tokens per second)
llama_print_timings: prompt eval time =     493.65 ms /   445 tokens (    1.11 ms per token,   901.45 tokens per second)
llama_print_timings:        eval time =     151.46 ms /     5 runs   (   30.29 ms per token,    33.01 tokens per second)
llama_print_timings:       total time =     678.38 ms /   450 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       4.03 ms /     6 runs   (    0.67 ms per token,  1489.57 tokens per second)
llama_print_timings: prompt eval time =     490.54 ms /   427 tokens (    1.15 ms per token,   870.48 tokens per second)
llama_print_timings:        eval time =     152.95 ms /     5 runs   (   30.59 ms per token,    32.69 tokens per second)
llama_print_timings:       total time =     677.60 ms /   432 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       4.27 ms /     6 runs   (    0.71 ms per token,  1405.48 tokens per second)
llama_print_timings: prompt eval time =     289.16 ms /   200 tokens (    1.45 ms per token,   691.66 tokens per second)
llama_print_timings:        eval time =     154.02 ms /     5 runs   (   30.80 ms per token,    32.46 tokens per second)
llama_print_timings:       total time =     477.46 ms /   205 tokens
Llama.generate: prefix-match hit

credit_card.

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       4.84 ms /     6 runs   (    0.81 ms per token,  1239.93 tokens per second)
llama_print_timings: prompt eval time =     263.24 ms /   146 tokens (    1.80 ms per token,   554.62 tokens per second)
llama_print_timings:        eval time =     152.96 ms /     5 runs   (   30.59 ms per token,    32.69 tokens per second)
llama_print_timings:       total time =     451.06 ms /   151 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       5.80 ms /    10 runs   (    0.58 ms per token,  1723.54 tokens per second)
llama_print_timings: prompt eval time =     404.75 ms /   365 tokens (    1.11 ms per token,   901.79 tokens per second)
llama_print_timings:        eval time =     280.09 ms /     9 runs   (   31.12 ms per token,    32.13 tokens per second)
llama_print_timings:       total time =     720.92 ms /   374 tokens
Llama.generate: prefix-match hit

mortgages_and_loans

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.10 ms /     6 runs   (    0.52 ms per token,  1934.86 tokens per second)
llama_print_timings: prompt eval time =     200.86 ms /    79 tokens (    2.54 ms per token,   393.30 tokens per second)
llama_print_timings:        eval time =     151.22 ms /     5 runs   (   30.24 ms per token,    33.07 tokens per second)
llama_print_timings:       total time =     372.90 ms /    84 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.49 ms /     6 runs   (    0.58 ms per token,  1717.23 tokens per second)
llama_print_timings: prompt eval time =     397.98 ms /   343 tokens (    1.16 ms per token,   861.86 tokens per second)
llama_print_timings:        eval time =     151.63 ms /     5 runs   (   30.33 ms per token,    32.97 tokens per second)
llama_print_timings:       total time =     571.71 ms /   348 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.25 ms /     6 runs   (    0.54 ms per token,  1845.59 tokens per second)
llama_print_timings: prompt eval time =     215.32 ms /   118 tokens (    1.82 ms per token,   548.02 tokens per second)
llama_print_timings:        eval time =     151.40 ms /     5 runs   (   30.28 ms per token,    33.02 tokens per second)
llama_print_timings:       total time =     386.37 ms /   123 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.27 ms /     6 runs   (    0.54 ms per token,  1837.67 tokens per second)
llama_print_timings: prompt eval time =     262.05 ms /   140 tokens (    1.87 ms per token,   534.24 tokens per second)
llama_print_timings:        eval time =     156.60 ms /     5 runs   (   31.32 ms per token,    31.93 tokens per second)
llama_print_timings:       total time =     438.54 ms /   145 tokens
Llama.generate: prefix-match hit

debt_collection.

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.29 ms /     6 runs   (    0.55 ms per token,  1825.37 tokens per second)
llama_print_timings: prompt eval time =     385.05 ms /   297 tokens (    1.30 ms per token,   771.33 tokens per second)
llama_print_timings:        eval time =     155.05 ms /     5 runs   (   31.01 ms per token,    32.25 tokens per second)
llama_print_timings:       total time =     560.69 ms /   302 tokens
Llama.generate: prefix-match hit

retail_banking

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.14 ms /     6 runs   (    0.52 ms per token,  1912.66 tokens per second)
llama_print_timings: prompt eval time =     495.06 ms /   427 tokens (    1.16 ms per token,   862.52 tokens per second)
llama_print_timings:        eval time =     159.14 ms /     5 runs   (   31.83 ms per token,    31.42 tokens per second)
llama_print_timings:       total time =     674.43 ms /   432 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.48 ms /     6 runs   (    0.58 ms per token,  1722.65 tokens per second)
llama_print_timings: prompt eval time =     213.86 ms /   110 tokens (    1.94 ms per token,   514.36 tokens per second)
llama_print_timings:        eval time =     152.65 ms /     5 runs   (   30.53 ms per token,    32.76 tokens per second)
llama_print_timings:       total time =     422.85 ms /   115 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       5.94 ms /     6 runs   (    0.99 ms per token,  1010.78 tokens per second)
llama_print_timings: prompt eval time =     286.81 ms /   159 tokens (    1.80 ms per token,   554.36 tokens per second)
llama_print_timings:        eval time =     143.76 ms /     5 runs   (   28.75 ms per token,    34.78 tokens per second)
llama_print_timings:       total time =     484.38 ms /   164 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.23 ms /     6 runs   (    0.54 ms per token,  1855.86 tokens per second)
llama_print_timings: prompt eval time =     523.28 ms /   512 tokens (    1.02 ms per token,   978.45 tokens per second)
llama_print_timings:        eval time =     155.76 ms /     5 runs   (   31.15 ms per token,    32.10 tokens per second)
llama_print_timings:       total time =     699.21 ms /   517 tokens
Llama.generate: prefix-match hit

credit_reporting

llama_print_timings:        load time =     649.71 ms
llama_print_timings:      sample time =       3.26 ms /     6 runs   (    0.54 ms per token,  1840.49 tokens per second)
llama_print_timings: prompt eval time =     212.12 ms /   102 tokens (    2.08 ms per token,   480.86 tokens per second)
llama_print_timings:        eval time =     158.42 ms /     5 runs   (   31.68 ms per token,    31.56 tokens per second)
llama_print_timings:       total time =     389.76 ms /   107 tokens

credit_reporting

In [25]:
new_data['mistral_response']

167           credit_card.
169       credit_reporting
461       debt_collection.
253       credit_reporting
42          retail_banking
369       credit_reporting
26     mortgages_and_loans
377       credit_reporting
238       credit_reporting
374       credit_reporting
140       credit_reporting
175       credit_reporting
388       credit_reporting
62     mortgages_and_loans
256       credit_reporting
332       credit_reporting
386       credit_reporting
56            credit_card.
157       credit_reporting
48     mortgages_and_loans
163       credit_reporting
9         credit_reporting
441       credit_reporting
102       debt_collection.
0           retail_banking
364       credit_reporting
139       credit_reporting
150       credit_reporting
173       credit_reporting
463       credit_reporting
Name: mistral_response, dtype: object

In [26]:
#Extracting a category label from text using regular expressions.
#Find a structured label first. If that fails, it falls back to searching for known category keywords.

#Creates a function that takes 1 piece of text as input
def extract_category(text):
    # Define the regex pattern to match "category:" or "Category:" followed by a word
    pattern = r'category:\s*(\w+)'

    # Use re.search with the re.IGNORECASE flag to make it case-insensitive
    match = re.search(pattern, text, re.IGNORECASE)

    # If a match is found, return the captured group, else return None
    if match:
        return match.group(1)
    else:
        pattern1 = r'(credit_card|retail_banking|credit_reporting|mortgages_and_loans|debt_collection)'
        match = re.search(pattern1, text, re.IGNORECASE)
        if match:
            return match.group()
        else:
            return ''

In [27]:
#Handles missing responses
#Extract structured labels like "Category: Credit_Card"
#Fall back to keyword search
#Defaults to "other" when nothing matches

import re

def extract_category(text):
    if not text:
        return "Other"

    # Match "Category: Something With Spaces"
    pattern = r'category:\s*([A-Za-z\s]+)'
    match = re.search(pattern, text, re.IGNORECASE)

    if match:
        return match.group(1).strip()

    # Fallback to known labels
    allowed = [
        "credit_card",
        "retail_banking",
        "credit_reporting",
        "mortgages_and_loans",
        "debt_collection",
        "Other"
    ]

    for cat in allowed:
        if cat.lower() in text.lower():
            return cat

    return "Other"

In [28]:
new_data['mistral_response_cleaned'] = new_data['mistral_response'].apply(lambda x: extract_category(x))

In [29]:
new_data.head()

,product,narrative,summary,mistral_response,mistral_response_cleaned
167,retail_banking,fraudulent charge totaling made capital one ch...,A fraudulent charge was made on the individual...,credit_card.,credit_card
169,credit_reporting,block except otherwise provided section consum...,The text outlines various stipulations regardi...,credit_reporting,credit_reporting
461,credit_card,usaa master plan collect cancellation debt usa...,The input appears to be a complaint about USAA...,debt_collection.,debt_collection
253,credit_reporting,block except otherwise provided section consum...,The text pertains to the stipulations and oper...,credit_reporting,credit_reporting
42,credit_reporting,open account acct opened balance account acct ...,The input is about various accounts being open...,retail_banking,retail_banking

In [30]:
f1 =  f1_score(new_data['product'], new_data['mistral_response_cleaned'],average='micro')
print(f'F1 Score: {f1}')

F1 Score: 0.8333333333333334

Since micro-averaging aggregates all true positives, false positives ,and false negatives globally, this score is equivalent to overall accuracy in a multi-class setting.

In [ ]:
f2 = f1_score(
    new_data['product'],
    new_data['mistral_response_cleaned'],
    average='micro'
)

print(f'F1 Score: {f2}')

F1 Score: 0.8333333333333334

F1 score for both mistral_response and mistral_response_cleaned is 0.8333, indicating that the cleaning step did not change the model's classification and performance.

The cleaning function mainly standardizes the output format of the model predictions (eg, extracting the category label and normalizing text). However, since the predicted categories remained the same before and after cleaning, the number of true positives, false positives, and false negative did not change.

Because the evaluation uses micro-average F1 score, which measures overall classification accuracy across all classes, the resulting score remains identical.

Therefore, the cleaning step improves the consistency of prediction labels but does not affect the model's predicitive performance in this dataset.