<a href="https://colab.research.google.com/github/EiMonSan-Ellie/LLM_RAG-Project/blob/main/Text_Classification_and_Compliant_Response.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installating and Importing the Necessary Libraries

In [2]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

Restart the session.

In [3]:
!pip install pandas==2.1.4

Requirement already satisfied: pandas==2.1.4 in /usr/local/lib/python3.12/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.1.4) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.1.4) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.1.4) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.1.4) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.1.4) (1.17.0)

**The Llama 2 Model**

In [4]:
# Installation for GPU llama-cpp-python
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.28  --force-reinstall --upgrade --no-cache-dir -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 138.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 293.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 351.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 295.3 MB/s eta 0:00:00
  Building wheel for llama-cpp-python (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas 2.1.4 requires numpy<2,>=1.26.0; python_version >= "3.12", but you have numpy 2.4.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.1.4 which is incompatible.
pointpats 2.5.5 requires pandas>=2.2, but you have pandas 2.1.4 which is incompatible.
mizani 0.13.5 requires pandas>=2.2.0, but you have pandas 2.1.4 which is incompatible.
tobler 0.14.0 requires pandas>=2.2, but you have pandas 2.1.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.5 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.1.4 which is incompatible.
xarray 2025.12.0 requires pandas>=2.2, but you have pandas 2.1.4 which is incompatible.

In [5]:
!pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

In [6]:
!pip install -q datasets==2.16.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.1.4 which is incompatible.
pointpats 2.5.5 requires pandas>=2.2, but you have pandas 2.1.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
mizani 0.13.5 requires pandas>=2.2.0, but you have pandas 2.1.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires pandas>=2.2, but you have pandas 2.1.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.1.4 which is incompatible.
xarray 2025.12.0 requires pandas>=2.2, but you have pandas 2.1.4 which is incompatible.

In [7]:
# Import the hf_hub_download function from the Hugging Face Hub library
from huggingface_hub import hf_hub_download

# Import the Llama class from the llama_cpp library
from llama_cpp import Llama

In [8]:
model_name_or_path = "TheBloke/Llama-2-13B-chat-GGUF"
model_basename = "llama-2-13b-chat.Q5_K_M.gguf" # the model is in gguf format

In [9]:
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

In [10]:
lcpp_llm = Llama(
    model_path=model_path,
    n_threads=2,
    n_batch=512,
    n_gpu_layers=43, # Change this value based on your model and your GPU VRAM pool.
    n_ctx=4096,
)

AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |

# Problem Statement 1: Text Classification - Sentiment Analysis

**Loading the IMDb Reviews Dataset**

In [11]:
import random
import pandas as pd
import numpy as np
np.float_ = np.float64

from datasets import load_dataset

In [12]:
dataset = load_dataset("imdb")

In [13]:
imdb_train_df = dataset['train'].to_pandas()
imdb_test_df = dataset['test'].to_pandas()

In [14]:
(imdb_train_df.shape, imdb_test_df.shape)

((25000, 2), (25000, 2))

Both the training and testing DataFrames have the same shape: 25,000 rows and 2 columns.

In [15]:
positive_examples = imdb_train_df.loc[imdb_train_df.label == 1, :].sample(3)
negative_examples = imdb_train_df.loc[imdb_train_df.label == 0, :].sample(3)

**positive_examples** containing three random positive sentiment examples, and

**negative_examples** containing three random negative sentiment examples.

In [16]:
positive_examples

                                                    text  label
22923  This movie is intelligent. That is, more than ...      1
19596  ***SPOILERS*** On of the first WWII movies com...      1
16216  This film is amazing - it's just like a nightm...      1

In [17]:
negative_examples

                                                   text  label
9348  If you liked the Grinch movie... go watch that...      0
9947  Why is it that any film about Cleopatra, the l...      0
3901  I managed to sneak away one night and go to th...      0

In [18]:
#concatenating the subsets of positive and negative sentiment examples (positive_examples and negative_examples)
examples = pd.concat([positive_examples, negative_examples]).to_json(orient='records')

**Sentiment Classification**

- In this problem statement, we will be working with the IMDb dataset of movie reviews, along with the labeled sentiment for each review.

- We will utilize a pre-trained Large Language Model as a Text Classification engine to do Sentiment Analysis. This will be done simply by prompting the model to play this role and giving it clear instructions to output as prediction only the Positive / Negative sentiment label associated with each review.

In [19]:
import json
import numpy as np
from collections import Counter
from tqdm import tqdm

In [20]:
system_message = """[INST]<<SYS>>Classify the sentiment of movie reviews presented in the input as 'positive' or 'negative'.
Movie reviews will be delimited by triple backticks in the input.
Answer only 'positive' or 'negative'. Do not explain your answer.

Instructions:
1. Carefully read the text of the review and consider the overall sentiment of the review
2. Estimate the probability of the review being positive

To re-iterate, your answer should strictly only contain the label: positive or negative.

Some examples of expected output are provided below as guidance.<</SYS>>[/INST]
"""

- The main content of the message provides instructions to the user on a specific task, which is to classify the sentiment of movie reviews as either 'positive' or 'negative'.
- It mentions that movie reviews will be delimited (separated) by triple backticks in the input.
- It emphasizes that the user should provide only the label ('positive' or 'negative') as the answer and should not explain their answer.
- Instructions are given, including reading the text of the review and estimating the probability of the review being positive.
The message also provides examples of expected output for guidance.

**Prompt Template**

In [21]:
prompt_template = """
[INST] ```{input_data}``` [/INST]
{output}
"""

In [22]:
## Initialize an empty string to store few-shot examples
few_shot_examples = ''

**Few-shot Learning**

"Few-shot Learning" is an ML paradigm where a model is trained to make predictions or perform tasks with very limited examples or "shots" of training data.

In traditional Machine Learning, models often require large amounts of labeled data for training. However, in few-shot learning, the goal is to enable a model to generalize and make accurate predictions or decisions when it has access to only a small number of examples.

In [23]:
## Iterate through each example in the JSON data which was created earlier
for example in json.loads(examples):
        # Extract the input data (text) from the example, excluding the 'label'

    example_input = {i:example[i] for i in example if i!='label'}
    # Determine the sentiment prediction based on the 'label' value
    if example['label'] == 0:
        example_prediction = 'negative'
    else:
        example_prediction = 'positive'

    # Concatenate the input data and the predicted sentiment
    # using a template and add it to the 'few_shot_examples' string

    few_shot_examples += prompt_template.format(
        input_data=example_input['text'],  ###input_data is used in the prompt_template
        output=example_prediction          ###outpu is used in the prompt_template
    )

In [24]:
test_rows = json.loads(
    imdb_test_df.sample(100).to_json(orient='records')
)

The test_rows will contain a list of dictionaries, where each dictionary represents a single row (example) from the **IMDb testing dataset**. This allows to work **with a subset of the testing data, specifically 100** randomly sampled rows, in a structured format within your Python code.

**Making Predictions with the LLM**

In [25]:
## Initialize empty lists to store model predictions and ground truth values.
model_predictions, ground_truths = [], []

In [26]:
## Iterate through each row in the test data with a progress bar
for row in tqdm(test_rows):
      # Extract the input data (text) from the current row, excluding the 'label'
    test_input = {i:row[i] for i in row if i!='label'}

        # Construct a few-shot prompt by combining system message, few-shot examples, and test input
    few_shot_prompt = (
        system_message + few_shot_examples +
        prompt_template.format(
            input_data=test_input['text'],
            output=''
        )
    )

    try:
        # Use the model (lcpp_llm) to generate a response based on the few-shot prompt
        response = lcpp_llm(
            prompt=few_shot_prompt,
            max_tokens=2,
            temperature=0,
            top_p=0.95,
            repeat_penalty=1.2,
            top_k=50,
            stop=['INST'], # Dynamic stopping when such token is detected.
            echo=False # do not return the prompt
        )
        # Extract the model's prediction from the response

        prediction = response["choices"][0]["text"]

        # Append the model's prediction to the 'model_predictions' list, lowercased and stripped of whitespace
        model_predictions.append(prediction.strip().lower())

        # Determine the ground truth label based on the row's 'label' value and append it to 'ground_truths'
        if row['label'] == 0:
            ground_truths.append('negative')
        else:
            ground_truths.append('positive')
    except ValueError as e:
          # Handle any ValueErrors that may occur during the process and continue with the next row

        print(e)
        continue

  1%|          | 1/100 [01:08<1:53:09, 68.58s/it]Llama.generate: prefix-match hit
  2%|▏         | 2/100 [01:13<50:48, 31.11s/it]  Llama.generate: prefix-match hit
  3%|▎         | 3/100 [01:18<31:15, 19.33s/it]Llama.generate: prefix-match hit
  4%|▍         | 4/100 [01:33<28:03, 17.54s/it]Llama.generate: prefix-match hit
  5%|▌         | 5/100 [01:40<21:48, 13.78s/it]Llama.generate: prefix-match hit
  6%|▌         | 6/100 [01:45<16:39, 10.64s/it]Llama.generate: prefix-match hit
  7%|▋         | 7/100 [02:01<19:30, 12.58s/it]Llama.generate: prefix-match hit
  8%|▊         | 8/100 [02:36<30:07, 19.64s/it]Llama.generate: prefix-match hit
  9%|▉         | 9/100 [02:48<26:02, 17.17s/it]Llama.generate: prefix-match hit
 10%|█         | 10/100 [02:57<21:56, 14.63s/it]Llama.generate: prefix-match hit
 11%|█         | 11/100 [03:01<17:09, 11.56s/it]Llama.generate: prefix-match hit
 12%|█▏        | 12/100 [03:16<18:08, 12.37s/it]Llama.generate: prefix-match hit
 13%|█▎        | 13/100 [03:22<15:08, 10.45s/it]Llama.generate: prefix-match hit
 14%|█▍        | 14/100 [03:34<15:51, 11.07s/it]Llama.generate: prefix-match hit
 15%|█▌        | 15/100 [03:42<14:27, 10.21s/it]Llama.generate: prefix-match hit
 16%|█▌        | 16/100 [03:57<16:10, 11.55s/it]Llama.generate: prefix-match hit
 17%|█▋        | 17/100 [04:06<15:07, 10.94s/it]Llama.generate: prefix-match hit
 18%|█▊        | 18/100 [04:13<13:20,  9.76s/it]Llama.generate: prefix-match hit
 19%|█▉        | 19/100 [04:29<15:41, 11.63s/it]Llama.generate: prefix-match hit
 20%|██        | 20/100 [04:38<14:26, 10.83s/it]Llama.generate: prefix-match hit
 21%|██        | 21/100 [05:04<19:55, 15.13s/it]Llama.generate: prefix-match hit
 22%|██▏       | 22/100 [05:12<16:56, 13.04s/it]Llama.generate: prefix-match hit
 23%|██▎       | 23/100 [05:20<14:54, 11.61s/it]Llama.generate: prefix-match hit
 24%|██▍       | 24/100 [05:45<19:40, 15.53s/it]Llama.generate: prefix-match hit
 25%|██▌       | 25/100 [05:52<16:24, 13.13s/it]Llama.generate: prefix-match hit
 26%|██▌       | 26/100 [06:00<14:03, 11.39s/it]Llama.generate: prefix-match hit
 27%|██▋       | 27/100 [06:27<19:35, 16.10s/it]Llama.generate: prefix-match hit
 28%|██▊       | 28/100 [06:35<16:31, 13.77s/it]Llama.generate: prefix-match hit
 29%|██▉       | 29/100 [06:44<14:29, 12.25s/it]Llama.generate: prefix-match hit
 30%|███       | 30/100 [06:55<13:46, 11.81s/it]Llama.generate: prefix-match hit
 31%|███       | 31/100 [07:09<14:27, 12.57s/it]Llama.generate: prefix-match hit
 32%|███▏      | 32/100 [07:33<18:14, 16.10s/it]Llama.generate: prefix-match hit
 33%|███▎      | 33/100 [08:01<21:53, 19.60s/it]Llama.generate: prefix-match hit
 34%|███▍      | 34/100 [08:05<16:22, 14.88s/it]Llama.generate: prefix-match hit
 35%|███▌      | 35/100 [08:31<19:49, 18.30s/it]Llama.generate: prefix-match hit
 36%|███▌      | 36/100 [08:52<20:21, 19.09s/it]Llama.generate: prefix-match hit
 37%|███▋      | 37/100 [09:03<17:27, 16.62s/it]Llama.generate: prefix-match hit
 38%|███▊      | 38/100 [09:28<19:51, 19.22s/it]Llama.generate: prefix-match hit
 39%|███▉      | 39/100 [09:41<17:34, 17.28s/it]Llama.generate: prefix-match hit
 40%|████      | 40/100 [09:45<13:23, 13.38s/it]Llama.generate: prefix-match hit
 41%|████      | 41/100 [09:53<11:32, 11.73s/it]Llama.generate: prefix-match hit
 42%|████▏     | 42/100 [10:11<13:08, 13.59s/it]Llama.generate: prefix-match hit
 43%|████▎     | 43/100 [11:10<25:44, 27.10s/it]Llama.generate: prefix-match hit
 44%|████▍     | 44/100 [11:19<20:16, 21.72s/it]Llama.generate: prefix-match hit
 45%|████▌     | 45/100 [11:25<15:45, 17.19s/it]Llama.generate: prefix-match hit
 46%|████▌     | 46/100 [11:52<18:02, 20.05s/it]Llama.generate: prefix-match hit
 47%|████▋     | 47/100 [12:06<16:02, 18.17s/it]Llama.generate: prefix-match hit
 48%|████▊     | 48/100 [12:16<13:42, 15.81s/it]Llama.generate: prefix-match hit
 49%|████▉     | 49/100 [12:24<11:19, 13.33s/it]Llama.generate: prefix-match hit
 50%|█████     | 50/100 [12:30<09:17, 11.15s/it]Llama.generate: prefix-match hit
 51%|█████     | 51/100 [12:46<10:17, 12.60s/it]Llama.generate: prefix-match hit
 52%|█████▏    | 52/100 [13:01<10:48, 13.50s/it]Llama.generate: prefix-match hit
 53%|█████▎    | 53/100 [13:14<10:17, 13.15s/it]Llama.generate: prefix-match hit
 54%|█████▍    | 54/100 [13:20<08:31, 11.11s/it]Llama.generate: prefix-match hit
 55%|█████▌    | 55/100 [13:29<07:42, 10.28s/it]Llama.generate: prefix-match hit
 56%|█████▌    | 56/100 [13:38<07:18,  9.96s/it]Llama.generate: prefix-match hit
 57%|█████▋    | 57/100 [13:44<06:23,  8.93s/it]Llama.generate: prefix-match hit
 58%|█████▊    | 58/100 [13:56<06:45,  9.66s/it]Llama.generate: prefix-match hit
 59%|█████▉    | 59/100 [14:04<06:19,  9.26s/it]Llama.generate: prefix-match hit
 60%|██████    | 60/100 [14:15<06:37,  9.94s/it]Llama.generate: prefix-match hit
 61%|██████    | 61/100 [14:26<06:34, 10.13s/it]Llama.generate: prefix-match hit
 62%|██████▏   | 62/100 [14:58<10:30, 16.60s/it]Llama.generate: prefix-match hit
 63%|██████▎   | 63/100 [15:07<08:51, 14.37s/it]Llama.generate: prefix-match hit
 64%|██████▍   | 64/100 [15:16<07:39, 12.75s/it]Llama.generate: prefix-match hit
 65%|██████▌   | 65/100 [15:47<10:38, 18.25s/it]Llama.generate: prefix-match hit
 66%|██████▌   | 66/100 [16:01<09:38, 17.01s/it]Llama.generate: prefix-match hit
 67%|██████▋   | 67/100 [16:08<07:45, 14.10s/it]Llama.generate: prefix-match hit
 68%|██████▊   | 68/100 [16:18<06:49, 12.79s/it]Llama.generate: prefix-match hit
 69%|██████▉   | 69/100 [16:24<05:36, 10.86s/it]Llama.generate: prefix-match hit
 70%|███████   | 70/100 [16:38<05:46, 11.56s/it]Llama.generate: prefix-match hit
 71%|███████   | 71/100 [16:50<05:39, 11.70s/it]Llama.generate: prefix-match hit
 72%|███████▏  | 72/100 [17:08<06:24, 13.73s/it]Llama.generate: prefix-match hit
 73%|███████▎  | 73/100 [17:21<06:03, 13.46s/it]Llama.generate: prefix-match hit
 74%|███████▍  | 74/100 [17:33<05:42, 13.16s/it]Llama.generate: prefix-match hit
 75%|███████▌  | 75/100 [18:03<07:31, 18.06s/it]Llama.generate: prefix-match hit
 76%|███████▌  | 76/100 [18:11<06:00, 15.02s/it]Llama.generate: prefix-match hit
 77%|███████▋  | 77/100 [18:19<05:00, 13.07s/it]Llama.generate: prefix-match hit
 78%|███████▊  | 78/100 [18:33<04:50, 13.20s/it]Llama.generate: prefix-match hit
 79%|███████▉  | 79/100 [19:11<07:15, 20.71s/it]Llama.generate: prefix-match hit
 80%|████████  | 80/100 [19:21<05:47, 17.38s/it]Llama.generate: prefix-match hit
 81%|████████  | 81/100 [19:30<04:45, 15.04s/it]Llama.generate: prefix-match hit
 82%|████████▏ | 82/100 [19:42<04:14, 14.16s/it]Llama.generate: prefix-match hit
 83%|████████▎ | 83/100 [20:01<04:22, 15.45s/it]Llama.generate: prefix-match hit
 84%|████████▍ | 84/100 [20:13<03:52, 14.51s/it]Llama.generate: prefix-match hit
 85%|████████▌ | 85/100 [20:20<03:02, 12.14s/it]Llama.generate: prefix-match hit
 86%|████████▌ | 86/100 [20:27<02:30, 10.76s/it]Llama.generate: prefix-match hit
 87%|████████▋ | 87/100 [20:57<03:31, 16.29s/it]Llama.generate: prefix-match hit
 88%|████████▊ | 88/100 [21:02<02:36, 13.06s/it]Llama.generate: prefix-match hit
 89%|████████▉ | 89/100 [21:12<02:14, 12.25s/it]Llama.generate: prefix-match hit
 90%|█████████ | 90/100 [21:17<01:39,  9.98s/it]Llama.generate: prefix-match hit
 91%|█████████ | 91/100 [21:56<02:47, 18.64s/it]Llama.generate: prefix-match hit
 92%|█████████▏| 92/100 [22:27<02:57, 22.24s/it]Llama.generate: prefix-match hit
 93%|█████████▎| 93/100 [22:34<02:03, 17.64s/it]Llama.generate: prefix-match hit
 94%|█████████▍| 94/100 [22:42<01:29, 14.96s/it]Llama.generate: prefix-match hit
 95%|█████████▌| 95/100 [22:50<01:04, 12.85s/it]Llama.generate: prefix-match hit
 96%|█████████▌| 96/100 [23:00<00:48, 12.08s/it]Llama.generate: prefix-match hit
 97%|█████████▋| 97/100 [23:08<00:32, 10.76s/it]Llama.generate: prefix-match hit
 98%|█████████▊| 98/100 [23:17<00:20, 10.33s/it]Llama.generate: prefix-match hit
 99%|█████████▉| 99/100 [23:47<00:16, 16.03s/it]Llama.generate: prefix-match hit
100%|██████████| 100/100 [24:42<00:00, 14.82s/it]

- The code iterates through each row in the test_rows dataset, displaying a progress bar using tqdm for tracking progress.

- For each row, it extracts the input data (text) from the current row, excluding the 'label', and stores it in the test_input dictionary.

- It constructs a few-shot prompt by combining a system message, a few-shot example, and the current test input. This prompt is designed to be used as input for the model.

- Inside a try-except block, it uses the machine learning model (lcpp_llm) to generate a response based on the few-shot prompt. Several parameters, such as max_tokens, temperature, and stop, are set to control the model's behavior during response generation.

- It extracts the model's prediction from the response and appends it to the model_predictions list. The prediction is converted to lowercase and stripped of whitespace for consistency.

- It determines the ground truth label based on the 'label' value in the current row and appends it to the ground_truths list.

- In case of a ValueError during the process, it prints an error message and continues with the next row.

- After the loop completes, model_predictions will contain the model's predictions for the test data, and ground_truths will contain the true or ground truth labels. These lists can then be used for evaluating the model's performance, such as calculating accuracy, precision, recall, or other relevant metrics.

In [27]:
Counter(model_predictions)

Counter({'positive': 61, 'negative': 39})

The model_predictions list as follows:

'**negative**': The model made 53 predictions with the label 'negative'.

'**positive**': The model made 47 predictions with the label 'positive'.

In [28]:
Counter(ground_truths)

Counter({'positive': 59, 'negative': 41})

This Counter object counts the occurrences of labels in the ground_truths list, which likely contains the true or ground truth labels for the test data.

**'negative'**: There are 56 instances in the dataset with the label 'negative'.

**'positive'**: There are 44 instances in the dataset with the label 'positive'.

**Accuracy on the Test Set**

In [29]:
ground_truths = np.array(ground_truths)
model_predictions = np.array(model_predictions)


#ground_truths contains the true labels (ground truth) for a set of examples.
#model_predictions contains the labels predicted by a machine learning model for the same set of examples.

In [ ]:
(ground_truths == model_predictions).mean()

An accuracy value of **0.95 (or 95%)** indicates that the model's predictions match the true labels for approximately 95% of the examples in the dataset. In other words, the model is correct in its classification for the vast majority of the examples - an example of the state-of-the-art performance that LLMs achieve in NLP tasks.

**Precision**

In [30]:
TP = ((model_predictions == 'positive') & (ground_truths == 'positive')).sum()
FP = ((model_predictions == 'positive') & (ground_truths == 'negative')).sum()
precision = TP / (TP+FP)

In [31]:
precision

0.9508196721311475

High accuracy (0.95) indicates that the model is making correct predictions for most movie reviews.

The high precision (0.9149) remains a positive sign, showing that when the model predicts a review as **"positive," or "negative " it is usually correct.**

The model is effective in correctly classifying both positive and negative sentiment

# Problem Statement 2: Complaint Response Generation - Text Generation

In this problem statement, we will be providing a dataset of complaint messages written by customers of a bank.

We will utilize a pre-trained Large Language Model as a Text Generation model, to generate the appropriate response to these complaints. This will also be done by providing specific instructions in the prompt that guide the model on what to keep in mind while giving this response.

In [32]:
dataset = load_dataset("AdiOO7/Bank_Complaints")

In [33]:
system_message = """[INST]<<SYS>>As a spokesperson person of a particular bank, you are tasked to give a public response to a user's complaint presented as input.
Instructions:
1. Carefully observe the intensity and severity of the complaint received as input.
2. Choose a carefully worded public response. You need to reply to every complaint, however, responding with "Company chooses not to provide a public response" is also a valid response.
Some examples of appropriate response are provided below as guidance.<</SYS>>[/INST]
"""

In [34]:
prompt_template = """
[INST] {input_example} [/INST]
{output_example}
"""

In [35]:
few_shot_examples = ''

In [36]:
for i in range(5):
    sample_document = dataset['train'][random.randint(0, 1829)]
    user_input_example = sample_document['Input']
    assistant_output_example = sample_document['Response']

    few_shot_examples += prompt_template.format(
        input_example=user_input_example,
        output_example=assistant_output_example
    )

In [37]:
test_document = dataset['train'][random.randint(0, 1829)]
new_complaint = test_document['Input']

In [38]:
few_shot_prompt = (
    system_message +
    few_shot_examples +
    prompt_template.format(
        input_example=new_complaint,
        output_example=''
    )
)

In [39]:
response = lcpp_llm(
    prompt=few_shot_prompt,
    max_tokens=256,
    temperature=0,
    top_p=0.95,
    repeat_penalty=1.2,
    top_k=50,
    stop=['INST'], # Dynamic stopping when such token is detected.
    echo=False # do not return the prompt
)

Llama.generate: prefix-match hit

In [40]:
new_complaint

'There is an account listed as in collections from XXXX XXXX. I do not know where this account came from as I have never been to XXXX XXXX. \n'

In [41]:
print(response["choices"][0]["text"])

We apologize for any inconvenience caused by the erroneous reporting of this account. We take these matters seriously and are currently investigating the situation. Please allow us some time to resolve this matter, and we will provide an update as soon as possible. Thank you for bringing this to our attention.